App_Userpage/urls.py
from django.urls import path
from .Userpage_views import userpage_render_view, user_update_view, password_update_view, EmailVerificationView
app_name='App_Userpage'

urlpatterns = [
    path('detail/', userpage_render_view, name = 'userpage_render_view'),
    path('update/', user_update_view, name = 'user_update_view'),
    path('update/password/emailcheck', EmailVerificationView.as_view(), name='email_check'),
    path('update/<user_id>/password/<user_token>', password_update_view, name = 'password_update_view'),

]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from rest_framework.authtoken import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Board.urls')),
    path('auth/', include('App_Auth.urls')),
    path('file/',include('App_Files.urls')),
    path('user/', include('App_Userpage.urls')),
    path('api/', include('App_API.urls')),
    path("api/auth", views.obtain_auth_token, name="obtain_auth_token"),
    path('api_auth/', include('rest_framework.urls', namespace='rest_framework')) # DRF 웹 로그인 
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


App_Board/models.py
from django.db import models
from django.urls import reverse
from App_Auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('App_Board:board_render_view', args=[self.slug])
        
class Board(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null = True, related_name='boards')
    post_author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_name = models.CharField(max_length=100)
    post_content = models.TextField(max_length=1000)
    post_views_counting = models.IntegerField(default=0)

    # 글 작성 일을 객체가 추가될 때 자동으로 설정
    created_date = models.DateTimeField(auto_now_add=True)
    # 글 수정 일을 수정될 때 자동으로 설정
    updated_date = models.DateTimeField(auto_now=True)
    
    # 해당 모델의 객체들의 정렬 기준을 설정 [ updated --> 내림차순 ]
    class Meta:
        ordering = ['-id']

    def __str__(self):
        # 객체를 출력할 떄 나타날 값
        return self.post_name 

    ## 객체의 상세화면 주소를 반환하게 만든다. ## 
    def get_absolute_url(self):
        return reverse('App_Board:post_render_view',  args = [str(self.id)])    

class EditLog(models.Model):
    post = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='editlogs')
    editor = models.ForeignKey(User, on_delete=models.CASCADE)
    edit_date = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return "게시글 : " + str(self.post) + ", 수정일 : " + str(self.edit_date)

def file_dir_path(instance, file):
    if instance.post.category.id == 3:
        return f'file/{instance.post.category}/{instance.post.post_author.company}/{file}'
    else:
        return f'file/{instance.post.category}/{instance.post.post_author.name}/{instance.post.id}/{file}'

def output_filesize(file):
    import math, os
    size_bytes = os.path.getsize(os.getcwd()+"/media/"+str(file))
    if size_bytes == 0:
        return "0B"
    size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
    i = int(math.floor(math.log(size_bytes, 1024)))
    p = math.pow(1024, i)
    s = round(size_bytes / p, 2)
    return "%s %s" % (s, size_name[i])

class Photo(models.Model):
    post = models.ForeignKey(Board, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to=file_dir_path, blank=True, null=True)

    def get_imagename(self):
        return str(self.image).split('/')[-1]

class Files(models.Model):
    post = models.ForeignKey(Board, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    file = models.FileField(upload_to=file_dir_path, blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def get_filename(self):
        return str(self.file).split('/')[-1]
    
    # 파일의 크기 출력
    def get_filesize(self):
        return output_filesize(self.file)

    # 파일의 생성 날짜 출력
    def get_filecreatetime(self):
        import os, time
        file_path = os.getcwd()+"/media/"+str(self.file)
        create_time = time.strftime("%Y년 %m월 %d일 %H:%M", time.localtime(os.path.getctime(file_path)))
        return create_time
    
    def get_filepath(self):
        return str(self.file)
    
    def __str__(self):
        # 객체를 출력할 떄 나타날 값
        return self.get_filename() 

App_Userpage/models.py
from django.db import models

App_Userpage/templates/User_update.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class = "row">
        <div class = "col-lg-5">
            <form method="post" action="{% url 'App_Userpage:user_update_view' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="email">사용자 Email</label>
                    <input type="email" class="form-control" name="email" id="email"
                           value="{{ user.email }}" readonly="true">
                </div>
                <div class="mb-3">
                    <label for="name">이름</label>
                    <input type="text" class="form-control" name="name" id="name"
                    value="{{ user.name }}">
                </div>
                <div class="mb-3">
                    <label for="phone_number">전화번호</label>
                    <input type="tel" class="form-control" name="phone_number" id="phone_number"
                           value="{{ user.phone_number }}">
                </div>
                <button type="submit" name = "action" value="save" style="width:100%; height:35px;" class="btn btn-sm text-light bg-dark mb-3">수정 완료</button>
            </form>
        </div>
        <div class="col-lg-4">
            {% include "form_errors.html" %}
        </div>
    </div>      
</div>
{% endblock %}

App_Userpage/templates/Userpage.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class = "row">
        <div class = "col-lg-4">
            <div class="mb-3">
                <label for="email">사용자 Email</label>
                <a class="form-control" readonly="true">{{ user.email }}</a>
            </div>
            <div class="mb-3">
                <label for="name">이름</label>
                <a class="form-control" readonly="true">{{user.name}}</a>
            </div>
            <div class="mb-3">
                <label for="phone_number">전화번호</label>
                <a class="form-control" readonly="true">{{user.phone_number}}</a>
            </div>
            <div class="mb-3">
                <label for="company" >회사명/회사코드</label>
                <a class="form-control" readonly="true">{{user.company}}</a>                
            </div>
            <a href="{% url 'App_Userpage:user_update_view' %}" class="btn btn-sm text-light bg-dark">
                회원정보 수정
            </a>
            <a href="{% url 'App_Userpage:password_update_view' user.id user_token %}" class="btn btn-sm text-light bg-dark">
                비밀번호 변경
            </a>
        </div>

        <div class = "col-lg-7">
            <h4>작성한 게시물</h4>
            <table class="table table-sm table-hover">
                <thead>
                <tr class="text-center">
                    <th>번호</th>
                    <th style="width:30%">제 목</th>
                    <th>소속</th>
                    <th>조회수</th>
                    <th>작성자</th>
                    <th>날짜</th>
                </tr>
                </thead>
                <tbody>
                {% if user.board_set.all %}
                {% for board in boards %} 
                <tr class="text-center">
                    <!-- 번호 -->
                    <td class="align-middle">
                        <span>{{board.id}}</span>
                    </td>
                    <!-- 제목 -->
                    <td class="text-left align-middle">                        
                        <a href="{{ board.get_absolute_url }}" class="subject-link">{{board.post_name}}</a>
                    <!-- 소속 -->
                    <td class="align-middle text-left small">
                        <small>{{board.post_author.company}}</small>
                    </td>
                    <td class="align-middle text-left small">
                        <small >{{board.post_views_counting}}</small>
                    </td>
                    <!-- 작성자 -->
                    <td class="align-middle text-left small">
                        <small>{{board.post_author.name}}</small>
                    </td>
                    <!-- 날짜 -->
                    <td class="align-middle" style="font-size:0.75em">
                        {% if board.updated_date == board.created_date%}
                        <small>{{board.created_date}}</small>
                        {% else %}
                        <small>{{board.updated_date}}(수정)</small>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <h4>  작성된 게시물이 없습니다.</h4>
                {% endif %}
                </tbody>
            </table>
        {% include "pagination.html" %}
        </div>
    </div>      
</div>
{% if messages %}
    {% for message in messages %}
        <div class="row" style="margin:20px auto;">
        <div class="col-sm-12">
            <div class="alert alert-success">
            <strong>{{ message.tags }}!</strong> {{ message.message }}
            </div>
        </div>
        </div>
    {% endfor %}
{% endif %}
{% endblock %}

App_Userpage/templates/password_update.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class = "row">
        <div class = "col-lg-5">
            <form method="post" action="{% url 'App_Userpage:password_update_view' user.id user_token %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="email">사용자 Email</label>
                    <input type="email" class="form-control" value="{{ email }}" readonly="true">
                </div>
                {% if request.user.is_authenticated %}
                <div class="mb-3">
                    <label for="password">기존의 비밀번호</label>
                    <input type="password" class="form-control" name="origin_password" id="origin_password">
                </div>
                {% endif %}
                <div class="mb-3">
                    <label for="password">새로운 비밀번호</label>
                    <input type="password" class="form-control" name="new_password" id="new_password">
                </div>
                <div class="mb-3">
                    <label for="password_check">새로운 비밀번호 확인</label>
                    <input type="password" class="form-control" name='password_check' id="password_check">
                </div>
                <button type="submit" style="width:100%; height:35px;" class="btn btn-sm text-light bg-dark mb-3">비밀번호 수정</button>
            </form>
        </div>
        {% if messages %}
        {% for message in messages %}
            <div class="row" style="margin:20px auto;">
            <div class="col-sm-12">
                <div class="alert alert-danger">
                <strong>{{ message.tags }}!</strong> {{ message.message }}
                </div>
            </div>
            </div>
        {% endfor %}
        {% endif %}
        <div class="col-lg-4">
            {% include "form_errors.html" %}
        </div>
    </div>      
</div>
{% endblock %}