App_Board/urls.py
from django.urls import path
from .views import edit_views, file_views, render_views

app_name='App_Board'

urlpatterns = [
    # base_views.py
    path('', render_views.mainpage_render_view, name = 'main_page'),
    path('<category_slug>/', render_views.board_render_view, name = 'board_render_view'),
    path('post/<int:board_id>', render_views.post_render_view, name = 'post_render_view'),

    # edit_views.py
    path('create/<category_id>', edit_views.post_create_view, name = 'post_create_view'),
    path('update/<int:board_id>', edit_views.post_update_view, name = 'post_update_view'),
    path('post/<int:pk>/delete', edit_views.post_delete.as_view(), name = 'post_delete_view'),

    # file_views.py
    path('post/download/<int:file_id>', file_views.file_download, name='file_download'),    
]


config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from rest_framework.authtoken import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Board.urls')),
    path('auth/', include('App_Auth.urls')),
    path('file/',include('App_Files.urls')),
    path('user/', include('App_Userpage.urls')),
    path('api/', include('App_API.urls')),
    path("api/auth", views.obtain_auth_token, name="obtain_auth_token"),
    path('api_auth/', include('rest_framework.urls', namespace='rest_framework')) # DRF 웹 로그인 
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


App_Board/models.py
from django.db import models
from django.urls import reverse
from App_Auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('App_Board:board_render_view', args=[self.slug])
        
class Board(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null = True, related_name='boards')
    post_author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_name = models.CharField(max_length=100)
    post_content = models.TextField(max_length=1000)
    post_views_counting = models.IntegerField(default=0)

    # 글 작성 일을 객체가 추가될 때 자동으로 설정
    created_date = models.DateTimeField(auto_now_add=True)
    # 글 수정 일을 수정될 때 자동으로 설정
    updated_date = models.DateTimeField(auto_now=True)
    
    # 해당 모델의 객체들의 정렬 기준을 설정 [ updated --> 내림차순 ]
    class Meta:
        ordering = ['-id']

    def __str__(self):
        # 객체를 출력할 떄 나타날 값
        return self.post_name 

    ## 객체의 상세화면 주소를 반환하게 만든다. ## 
    def get_absolute_url(self):
        return reverse('App_Board:post_render_view',  args = [str(self.id)])    

class EditLog(models.Model):
    post = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='editlogs')
    editor = models.ForeignKey(User, on_delete=models.CASCADE)
    edit_date = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return "게시글 : " + str(self.post) + ", 수정일 : " + str(self.edit_date)

def file_dir_path(instance, file):
    if instance.post.category.id == 3:
        return f'file/{instance.post.category}/{instance.post.post_author.company}/{file}'
    else:
        return f'file/{instance.post.category}/{instance.post.post_author.name}/{instance.post.id}/{file}'

def output_filesize(file):
    import math, os
    size_bytes = os.path.getsize(os.getcwd()+"/media/"+str(file))
    if size_bytes == 0:
        return "0B"
    size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
    i = int(math.floor(math.log(size_bytes, 1024)))
    p = math.pow(1024, i)
    s = round(size_bytes / p, 2)
    return "%s %s" % (s, size_name[i])

class Photo(models.Model):
    post = models.ForeignKey(Board, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to=file_dir_path, blank=True, null=True)

    def get_imagename(self):
        return str(self.image).split('/')[-1]

class Files(models.Model):
    post = models.ForeignKey(Board, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    file = models.FileField(upload_to=file_dir_path, blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def get_filename(self):
        return str(self.file).split('/')[-1]
    
    # 파일의 크기 출력
    def get_filesize(self):
        return output_filesize(self.file)

    # 파일의 생성 날짜 출력
    def get_filecreatetime(self):
        import os, time
        file_path = os.getcwd()+"/media/"+str(self.file)
        create_time = time.strftime("%Y년 %m월 %d일 %H:%M", time.localtime(os.path.getctime(file_path)))
        return create_time
    
    def get_filepath(self):
        return str(self.file)
    
    def __str__(self):
        # 객체를 출력할 떄 나타날 값
        return self.get_filename() 

App_Board/views.py
from django.contrib import messages
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.http import HttpResponse
from django.utils import timezone
from django.views import generic
# 함수형 뷰에서 사용하는 권한 제한
from django.contrib.auth.decorators import login_required
# 클레스형 뷰애서 사용하는 권한 제한
from django.contrib.auth.mixins import LoginRequiredMixin


def board_home(request):
    categories = Category.objects.all()
    return render(request, 'Board_home.html',{'categories' : categories})

def post_in_category(request, category_slug = None):
    current_category = None
    categories = Category.objects.all()
    boards = Board.objects.all()

    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        boards = boards.filter(category=current_category)

    context = {'current_category' : current_category, 'categories' : categories, 'boards' : boards}
    return render(request, 'Board_index.html', context)
    
def post_detail(request, board_id):
    board = get_object_or_404(Board, id=board_id)
    categories = Category.objects.all()
    current_category = get_object_or_404(Category, id = board.category.id)
    context = { 
        'board':board, 
        'categories' : categories, 
        'current_category': current_category,
      }
    return render(request, 'Board_post.html', context)   

@login_required(login_url='App_Auth:login')
def post_create(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    categories = Category.objects.all()

    if request.method == 'POST':
        if request.POST['action'] == 'save':
            form = BoardForm(request.POST, request.FILES)
            print('save 진행 1')
            if form.is_valid():
                print('save 진행 2')
                # 게시판 폼에 추가
                Board = form.save(commit=False)
                Board.created_date = timezone.now()
                Board.category = get_object_or_404(Category, id=category_id)
                Board.post_author = request.user
                Board.save()   
                print("보드 저장")
                return redirect("App_Board:post_detail", Board.id)
            return render(request, 'Board_create.html',{'categories' : categories, 'current_category' : category,})
    else:
        form = BoardForm() # -> unboundForm

    context = {'form': form, 'categories' : categories, 'current_category' : category,}
    return render(request, 'Board_create.html', context)

@login_required(login_url='App_Auth:login')
def post_update(request, board_id):
    categories = Category.objects.all()
    board = get_object_or_404(Board, id=board_id)
    if request.user.company == board.post_author.company or request.user.company == 'admin' :
        if request.method == "POST":
            form = BoardForm(request.POST, request.FILES, instance=board)
            if form.is_valid():
                # 게시판 폼에 추가
                board = form.save(commit=False)
                board.updated_date = timezone.now()  # 수정일시 저장
                board.save()
                form_edit = EditLogForm()
                editlog = form_edit.save(commit=False)
                editlog.edit_date = timezone.now()
                editlog.editor = request.user
                editlog.board_id = board_id
                editlog.save()
                return redirect("App_Board:post_detail", board.id)
        else:
            form = BoardForm(instance=board)

        context = {'form': form, 'categories' : categories, 'board' : board}
        return render(request, 'Board_create.html', context)
    else:
        messages.error(request, '수정권한이 없습니다')
        return redirect("App_Board:post_detail", board_id=board_id)
    
class post_delete(LoginRequiredMixin, generic.DeleteView):
    model = Board
    success_url = '/'
    template_name = 'Board_delete.html'
   
    def get_context_data(self, **kwargs):
        context = super(post_delete, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

def file_download(request, board_id):
    print('실행 1')
    board = get_object_or_404(Board, id=board_id)
    path = str(board.file)
    file_name = path.split('/')[-1]
    print(file_name)
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    # print(file_path)
 
    if os.path.exists(file_path):
        binary_file = open(file_path, 'rb')
        response = HttpResponse(binary_file.read(), content_type="multipart/formed-data")
        # print(response)
        response['Content-Disposition'] = 'attachment; filename=' + file_name
        return response
    else:
        message = '알 수 없는 오류가 발행하였습니다.'
        return HttpResponse("<script>alert('"+ message +"');history.back()'</script>")

App_Board/views/edit_views.py
from ..models import *
from ..forms import *
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect


# 함수형 뷰에서 사용하는 권한 제한
from django.contrib.auth.decorators import login_required
# 클레스형 뷰애서 사용하는 권한 제한
from django.contrib.auth.mixins import LoginRequiredMixin

all_category = Category.objects.all()

@login_required(login_url='App_Auth:login')
def post_create_view(request, category_id):
    select_category = get_object_or_404(Category, id = category_id)
    context = {
        'all_category' : all_category, 
        'select_category' : select_category
    }
    # 공지사항 작성 권한 분리
    if str(select_category) == "공지사항" and not request.user.is_admin :
        messages.error(request, '작성권한이 없습니다')
        return redirect("App_Board:board_render_view",select_category.slug)

    if request.method == 'POST' and request.POST['action'] == 'save':
        form = BoardForm(request.POST) # -> boundForm
        if form.is_valid():
            # 게시판 폼에 추가
            post = form.save(commit=False)
            post.created_date = timezone.now()
            post.category = get_object_or_404(Category, id=category_id)
            post.post_author = request.user
            post.save()   
            # 첨부 이미지 및 파일 저장을 위한 함수 호출
            return handle_save_action(request, post = post)     
           
        context['form'] = form
        return render(request, 'Board_create.html',context)
    else:
        context['form'] = BoardForm() # -> unboundForm

    return render(request, 'Board_create.html', context)

@login_required(login_url='App_Auth:login')
def post_update_view(request, board_id):
    select_post = get_object_or_404(Board, id=board_id)

    if request.user.company == select_post.post_author.company or request.user.is_admin :
        if request.method == "POST":
            form = BoardForm(request.POST, instance=select_post)# -> boundForm
            form_edit = EditLogForm()
            if form.is_valid():
                action = request.POST['action']
                # 게시판 폼에 추가
                select_post = form.save(commit=False)
                select_post.updated_date = timezone.now()  # 수정일시 저장
                select_post.save()

                if action == 'save':
                    return handle_save_action(request, post = select_post, form_edit = form_edit)
                                        
                elif action.startswith("delete"):
                    del_id = action[7:]
                    handle_delete_action(del_id)
                    
        else:
            form = BoardForm(instance=select_post)

        context = {
            'form': form, 
            'all_category' : all_category, 
            'select_post' : select_post
        }
        return render(request, 'Board_create.html', context)
    else:
        messages.error(request, '수정권한이 없습니다')
        return redirect("App_Board:post_render_view", board_id = board_id)
    
def handle_save_action(request, post, form_edit = None):
    for image in request.FILES.getlist('image'):
        photo = Photo()
        photo.post = post
        photo.image = image
        photo.save()

    for file in request.FILES.getlist('file'):
        files = Files()
        files.post = post
        files.user = request.user
        files.file = file
        files.save()
    
    if form_edit:
        editlog = form_edit.save(commit=False)
        editlog.edit_date = timezone.now()
        editlog.editor = request.user
        editlog.post = post
        editlog.save()

    return redirect('App_Board:post_render_view', post.id)

def handle_delete_action(del_id):
    if del_id[0] == 'i':
        image = Photo.objects.get(pk=del_id[1:])
        # file_delete(image_id=image.id) # 디렉토리에서 파일 삭제 함수
        image.delete()
    else:
        file = Files.objects.get(pk=del_id[1:])
        # file_delete(file_id=file.id)
        file.delete()

class post_delete(LoginRequiredMixin, generic.DeleteView):
    model = Board
    success_url = '/'
    template_name = 'Board_delete.html'
   
    def get_context_data(self, **kwargs):
        context = super(post_delete, self).get_context_data(**kwargs)
        context['all_category'] = all_category
        return context


App_Board/views/file_views.py
from ..models import *
from ..forms import *
import mimetypes # 한글 파일을 위한 패키진
import urllib
import os
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.http import HttpResponse


def file_download(request, file_id = None):
    if file_id :
        file = get_object_or_404(Files, id=file_id)
        path = file.get_filepath()
        file_name = file.get_filename()
    elif file_id == 0:
        file_name = "다중 압축 파일.zip"
        path = "file/관리/압축 파일/Multizip.zip"
    file_name = urllib.parse.quote(file_name.encode('utf-8'))
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    
    if os.path.exists(file_path):
        binary_file = open(file_path, 'rb')
        response = HttpResponse(binary_file.read(), content_type=mimetypes.guess_type(file_name))
        response['Content-Disposition'] = 'attachment; filename*=UTF-8\'\'%s' % file_name
        return response
    



App_Board/views/render_views.py
from django.shortcuts import render, get_object_or_404
from App_Board.models import *
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# 메인 페이지 
def mainpage_render_view(request):
    all_category = Category.objects.all()
    return render(request, 'Board_home.html',{'all_category' : all_category})

# 카테고리별 게시판 페이지
def board_render_view(request, category_slug = None):
    all_category = Category.objects.all()
    all_board = Board.objects.all()
    
    if category_slug:
        select_category = get_object_or_404(Category, slug=category_slug)
        select_board = all_board.filter(category=select_category)
        page = request.GET.get('page', '1')
        page_obj = pagination(page, select_board, 5)
    else:
        select_category = None
    
    context = {
        'select_category' : select_category, 
        'all_category' : all_category, 
        'select_board' : page_obj,
        'page_obj': page_obj
        }
    return render(request, 'Board_index.html', context)
    
# 게시글 상세 페이지
def post_render_view(request, board_id):
    all_category = Category.objects.all()
    select_post = get_object_or_404(Board, id=board_id)
    select_post.post_views_counting += 1 
    select_post.save()
    for key, value in request.session.items():
        print(f"Key: {key}, Value: {value}")
    editlogs = select_post.editlogs.all()
    select_category = get_object_or_404(Category, id = select_post.category.id)
    if select_category == "자료 취합":
        pass
    else:
        context = { 
            'select_post':select_post, 
            'all_category' : all_category, 
            'select_category': select_category,
            'editlogs' : editlogs,
        }
    return render(request, 'Board_post.html', context)

def pagination(page, model, set_num):
    # Paginator(쿼리셋, 한 페이지에 몇개의 포스트를 볼지 설정)
    paginator = Paginator(model, set_num)
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger: # page 값이 없을 때
        page = 1
        page_obj = paginator.page(page)
    except EmptyPage: # page를 너무 크게 입력하는 경우
        page = paginator.num_pages # 가장 마지막 page를 출력
        page_obj = paginator.page(page)
    return page_obj
   

App_Board/templates/Board_Index.html
{% extends "base.html" %}
{% block content %}
<h5 class="border-bottom pb-2 mb-3">{{select_category.name}}</h5>
<div class="content_block">
    <div class="table-responsive">
        <table class="table table-sm table-hover">
            <thead>
                <tr class="text-center">
                <th>번호</th>
                <th style="width:40%">제 목</th>
                <th>소속</th>
                <th>조회수</th>
                <th>작성자</th>
                <th>날짜</th>
            </tr>
            </thead>
            <tbody>
            {% if select_board %}
            {% for board in select_board %} 
            <tr class="text-center">
                <!-- 번호 -->
                <td class="align-middle">
                    <span>{{board.id}}</span>
                </td>
                <!-- 제목 -->
                <td class="text-left align-middle">                        
                    <a href="{{ board.get_absolute_url }}" class="subject-link">{{board.post_name}}</a>
                <!-- 소속 -->
                <td class="align-middle text-left small">
                    <small>{{board.post_author.company}}</small>
                </td>
                <td class="align-middle text-left small">
                    <small >{{board.post_views_counting}}</small>
                </td>
                <!-- 작성자 -->
                <td class="align-middle text-left small">
                    <small>{{board.post_author.name}}</small>
                </td>
                <!-- 날짜 -->
                <td class="align-middle" style="font-size:0.75em">
                    {% if board.updated_date == board.created_date%}
                    <small>{{board.created_date}}</small>
                    {% else %}
                    <small>{{board.updated_date}}(수정)</small>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <h4>  작성된 게시물이 없습니다.</h4>
            {% endif %}
            </tbody>
        </table>
        <a href="{% url 'App_Board:post_create_view' select_category.id %}" class="btn btn-sm text-light bg-dark" style="margin-left: 91%;">게시물 작성</a>
        {% if messages %}
        {% for message in messages %}
            <div class="row" style="margin:20px auto;">
            <div class="col-sm-12">
                <div class="alert alert-danger">
                <strong>{{ message.tags }}!</strong> {{ message.message }}
                </div>
            </div>
            </div>
        {% endfor %}
        {% endif %}
    </div>  
</div>
{% include "pagination.html" %}
{% endblock %}

App_Board/templates/Board_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">
        {% if select_post.category.name %} 
        {{select_post.category.name}} - 게시물 수정
        {% else %}
        {{select_category.name}} - 게시물 작성
        {% endif %}
    </h5>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <input type="text" class="form-control" name="post_name" id="post_name"  placeholder="제목을 입력하세요" value="{{ select_post.post_name }}">
        </div>
        <div class="mb-3">
            <textarea class="form-control" style="height: 200px;" name="post_content" id="post_content" placeholder="내용을 입력하세요.">{{select_post.post_content}}</textarea>
        </div>
        {% comment %} 이미지 첨부 시작{% endcomment %}
        <div class="mb-3">
            <strong>이미지 첨부</strong>
            <input type="file" class="form-control" name="image" id="image" accept="image/*" multiple>
        </div>
        {% if select_post.photo_set.all %}
        <table class="table table-sm table-hover">
            <thead>
            <tr class="text-center">
                <th style="width:45%">이미지</th>
                <th style="width:10%"></th>
            </tr>
            </thead>
            <tbody class="text-center">
                {% for image in select_post.photo_set.all %}
                <tr>
                    <td><a href='image.image.url'>{{image.get_imagename}}</a></td>
                    <td><button type="submit" name="action" value="delete_i{{image.id}}"  class="btn btn-danger"  style="width:100px;">삭제</button></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {%endif%}
        {% comment %} 이미지 첨부 끝 {% endcomment %}

        {% comment %} 파일 첨부 시작 {% endcomment %}
        <div class="mb-3">
            <strong>파일 첨부</strong>
            <input type="file" class="form-control" name="file" id="file" multiple>
        </div>
        {% if select_post.files_set.all %}
        <table class="table table-sm table-hover">
            <thead>
            <tr class="text-center">
                <th style="width:45%">첨부 파일</th>
                <th style="width:10%"></th>
            </tr>
            </thead>
            <tbody class="text-center">
                {% for file in select_post.files_set.all %}
                <tr>
                    <td><a href='file.file.url'>{{file.get_filename}}</a></td>
                    <td><button type="submit" name="action" value="delete_f{{file.id}}"  class="btn btn-danger"  style="width:100px;">삭제</button></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {%endif%}
        {% comment %} 파일 첨부 끝 {% endcomment %}
        
        <div class="mb-3">
            <button type="submit" name = "action" value="save" class="btn btn-sm text-light bg-dark"  style="width:100px; margin-left: 90%;" >저장하기</button>
        </div>
        <!-- File Section Start -->
        {% if board.file %}
        <table class="table table-sm table-hover">
            <thead>
            <tr class="text-center">
                <th style="width:45%">문서명</th>
                <th>작성자</th>
                <th>날짜</th>
                <th style="width:10%"></th>
            </tr>
            </thead>
            <tbody class="text-center">
                <tr>
                    <td><a href="{% url 'App_Board:file_download' board.id %}">{{board.get_filename}}</a></td>
                    <td>{{board.post_author}}</td>
                    <td>{{board.created_date}}</td>
                    <td><button type="submit" name="action" value="delete" class="btn btn-danger"  style="width:100px;">삭제</button></td>
                </tr>
            </tbody>
        </table>
        {%endif%}
        <!-- File Section End -->
        {% if form.errors %}
        <div class="alert alert-danger">제목과 내용은 필수입니다.</div>
        {% endif %}
    </form>  
</div>
{% endblock %}

App_Board/templates/Board_index.html
{% extends "base.html" %}
{% block content %}
<h5 class="border-bottom pb-2 mb-3">{{select_category.name}}</h5>
<div class="content_block">
    <div class="table-responsive">
        <table class="table table-sm table-hover">
            <thead>
                <tr class="text-center">
                <th>번호</th>
                <th style="width:40%">제 목</th>
                <th>소속</th>
                <th>조회수</th>
                <th>작성자</th>
                <th>날짜</th>
            </tr>
            </thead>
            <tbody>
            {% if select_board %}
            {% for board in select_board %} 
            <tr class="text-center">
                <!-- 번호 -->
                <td class="align-middle">
                    <span>{{board.id}}</span>
                </td>
                <!-- 제목 -->
                <td class="text-left align-middle">                        
                    <a href="{{ board.get_absolute_url }}" class="subject-link">{{board.post_name}}</a>
                <!-- 소속 -->
                <td class="align-middle text-left small">
                    <small>{{board.post_author.company}}</small>
                </td>
                <td class="align-middle text-left small">
                    <small >{{board.post_views_counting}}</small>
                </td>
                <!-- 작성자 -->
                <td class="align-middle text-left small">
                    <small>{{board.post_author.name}}</small>
                </td>
                <!-- 날짜 -->
                <td class="align-middle" style="font-size:0.75em">
                    {% if board.updated_date == board.created_date%}
                    <small>{{board.created_date}}</small>
                    {% else %}
                    <small>{{board.updated_date}}(수정)</small>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <h4>  작성된 게시물이 없습니다.</h4>
            {% endif %}
            </tbody>
        </table>
        <a href="{% url 'App_Board:post_create_view' select_category.id %}" class="btn btn-sm text-light bg-dark" style="margin-left: 91%;">게시물 작성</a>
        {% if messages %}
        {% for message in messages %}
            <div class="row" style="margin:20px auto;">
            <div class="col-sm-12">
                <div class="alert alert-danger">
                <strong>{{ message.tags }}!</strong> {{ message.message }}
                </div>
            </div>
            </div>
        {% endfor %}
        {% endif %}
    </div>  
</div>
{% include "pagination.html" %}
{% endblock %}

App_Board/templates/Board_post.html
{% extends "base.html" %}
{% block content %}
<h5 class="border-bottom pb-2 mb-3">{{select_category.name}} > {{select_post.post_name}}</h5>
<div style="padding-inline: 5%; padding-top: 2%;">
    <div class="pb-3 mb-0 border-bottom border-secondary font-weight-bold">
        <table width="100%">
        <tr>
            <td width="48%"><h5>{{select_post.post_name}}</h5></td>
            <td width="10" style="font-size:0.75em">조회수 : {{select_post.post_views_counting}}</td>
            <td width="17%" style="font-size:0.75em">작성자 : {{select_post.post_author.company}}({{select_post.post_author.name}})</td>
            <td width="25%" style="font-size:0.75em">
                <small>< 개시 : {{select_post.created_date}}></small>
                {% if select_post.updated_date != select_post.created_date%}
                <br><small>< 수정 : {{select_post.updated_date}}></small>
                {% endif %}
            </td>
        </tr>
        </table>
    </div>
    <div class="mt-3 mark-content" style="margin: 5%;">{{select_post.post_content|linebreaks}}</div>
    {% comment %} 이미지 추가 {% endcomment %}
    {% for image in select_post.photo_set.all %}
        <img src = "{{image.image.url }}" width="300"><br>
    {% endfor %}

    {% if messages %}
    {% for message in messages %}
        <div class="row" style="margin:20px auto;">
        <div class="col-sm-12">
            <div class="alert alert-danger">
            <strong>{{ message.tags }}!</strong> {{ message.message }}
            </div>
        </div>
        </div>
    {% endfor %}
    {% endif %}
    {% if request.user.company == select_post.post_author.company or request.user.is_admin %}
    <table width="100%" class="border-top pb-2 mb-3">
        <tr>
            <td width="78%"></td>
            <td width="11%">
                <a href="{% url 'App_Board:post_update_view' select_post.id  %}" class="btn btn-sm text-light bg-dark">게시물 수정</a>
            </td>
            <td width="11%">
                <a href="{% url 'App_Board:post_delete_view' select_post.id  %}" class="btn btn-sm text-light bg-dark">게시물 삭제</a>
            </td>
        </tr>
    </table>
    {%endif%}
    
    <!-- File Section Start -->
    {% if request.user.company == select_post.post_author.company or request.user.company == 'admin' or select_post.category.name == "공지사항"%} 
    <table class="table table-sm table-hover">
        <thead>
        <tr class="text-center">
            <th style="width:50%">문서명</th>
            <th>작성자</th>
            <th>날짜</th>
        </tr>
        </thead>
        <tbody class="text-center">
            {% for file in select_post.files_set.all %}
            <tr>
                <td>
                    <a href="{% url 'App_Board:file_download' file.id %}">
                        {{file.get_filename}}
                    </a>
                    <small>
                        [{{file.get_filesize}}]
                    </small>
                </td>
                <td>{{file.user}}</td>
                <td>{{file.get_filecreatetime}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {%endif%}
    <!-- File Section End -->

    <!-- Edit log Section Start -->
    {% if request.user.company == select_post.post_author.company or request.user.is_admin %}
    <table class="table table-sm table-hover">
        <thead>
        <tr class="text-center">
            <th style="width:30%">수정자</th>
            <th>수정 날짜</th>
        </tr>
        </thead>

        <tbody class="text-center">
            {% for editlog in editlogs reversed %}
            <tr>
                <td>{{editlog.editor}}</td>
                <td>{{editlog.edit_date}}</td>
                <td>수정</td>
            </tr>
            {% endfor%}
            <tr>
                <td>{{select_post.post_author.name}}</td>
                <td>{{select_post.created_date}}</td>
                <td>작성</td>
            </tr>
        </tbody>
    </table>
    <!-- Edit log Section End -->
    {% endif %}
</div>
{% endblock %}