App_Auth/urls.py
from django.urls import path
from . import Auth_views, EmailFunc
app_name = "App_Auth"

urlpatterns = [
    path('login/', Auth_views.login_view, name='login'),
    path('logout/', Auth_views.logout_view, name='logout'),
    path('sign/', Auth_views.SignupView.as_view(), name='signup'),
]

App_Userpage/urls.py
from django.urls import path
from .Userpage_views import userpage_render_view, user_update_view, password_update_view, EmailVerificationView
app_name='App_Userpage'

urlpatterns = [
    path('detail/', userpage_render_view, name = 'userpage_render_view'),
    path('update/', user_update_view, name = 'user_update_view'),
    path('update/password/emailcheck', EmailVerificationView.as_view(), name='email_check'),
    path('update/<user_id>/password/<user_token>', password_update_view, name = 'password_update_view'),

]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from rest_framework.authtoken import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Board.urls')),
    path('auth/', include('App_Auth.urls')),
    path('file/',include('App_Files.urls')),
    path('user/', include('App_Userpage.urls')),
    path('api/', include('App_API.urls')),
    path("api/auth", views.obtain_auth_token, name="obtain_auth_token"),
    path('api_auth/', include('rest_framework.urls', namespace='rest_framework')) # DRF 웹 로그인 
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


App_Auth/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.core.validators import RegexValidator

# 사용자 생성 및 관리 기능을 구현
class UserManager(BaseUserManager):    
    use_in_migrations = True    
    # 파라미터를 받아서 새로운 사용자를 생성하고 저장
    def create_user(self, email, name, phone_number, company, password):        
        if not email:            
            raise ValueError('이메일은 필수입니다.')
        if not password:            
            raise ValueError('비밀번호는 필수입니다.')
 
        user = self.model(            
            email=self.normalize_email(email),
            name = name,       
            phone_number = phone_number,
            company = company
        )        
        user.set_password(password)        
        user.save(using=self._db)        
        return user

    # create_user를 호출하여 관리자 권한을 추가로 설정
    def create_superuser(self, email, name, phone_number, company, password):        
    
        user = self.create_user(            
            email = self.normalize_email(email),
            name = name,       
            phone_number = phone_number,
            company = company,                      
            password = password,        
        )
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user 

class User(AbstractBaseUser, PermissionsMixin):    
    objects = UserManager()
    email = models.EmailField(max_length=255, unique=True, verbose_name='이메일')
    name = models.CharField(max_length=30, verbose_name='이름')
    phoneNumberRegex = RegexValidator(regex = r'^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')
    phone_number = models.CharField(validators = [phoneNumberRegex], max_length = 11, unique = True, verbose_name='전화번호')
    company = models.CharField(max_length=30, verbose_name='회사명/회사코드')
    
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
 
    USERNAME_FIELD = 'email'    # -> 사용자 고유 식별 필드 설정
    REQUIRED_FIELDS = ['name','phone_number','company'] # -> 슈퍼유저를 생성할때 필요한 필드 설정
 
    def __str__(self):
        return self.name
 
    @property
    def is_staff(self):
        return self.is_admin

App_Auth/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput)
    password_check = forms.CharField(label='비밀번호 확인', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'name', 'phone_number', 'company')

    # clean_<Field_name>() : 해당 필드의 유효성을 체크하는 메소드
    # 유효성 검사
    # 입력한 비밀번호의 일치 확인
    def clean_password_check(self):
        # self.cleaned_data['데이터'] : 데이트를 획득
        password = self.cleaned_data.get("password")
        password_check = self.cleaned_data.get("password_check")
        if password and password_check and password != password_check:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다!")
        return password_check

    # 입력한 이메일의 중복존재 여부 확인
    def clean_email(self):
        email = self.cleaned_data.get('email')
        # 이메일 검증시 대소문자를 구별하지 않는다.
        if User.objects.filter(email__iexact = email).exists():
            raise forms.ValidationError('이미 존재하는 이메일입니다. 다시 확인해주세요.')
        return email

    # 비밀번호를 해쉬 암호 방식으로 저장하고, 기존의 save 메소드를 호출하여 사용자를 지정한다.
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ('name', 'phone_number')

    
class UserPasswordChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput)
    password_check = forms.CharField(label='비밀번호 확인', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('password', )

    def clean_password_check(self):
        # self.cleaned_data['데이터'] : 데이트를 획득
        password = self.cleaned_data.get("password")
        password_check = self.cleaned_data.get("password_check")
        if password and password_check and password != password_check:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다!")
        return password_check
     
        
class UserCompanyChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('company', )


App_Auth/templates/email_verification.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class = "row">
        <div class = "col-lg-5">
            <form method="post" action="{% url 'App_Userpage:email_check' %}">
                {% csrf_token %}
                {% if email %}
                <div class="mb-3">
                    <label for="email">사용자 Email</label>
                    <input type="email" class="form-control" name="email" id="email"
                        value="{{email}}" readonly="true">
                </div>
                <div class="mb-3">
                    <label for="number">인증 코드</label>
                    <input type="text" class="form-control" name="code" id="code" placeholder = "대소문자 구별">
                </div>
                <button type="submit" name="action" value="check_code" style="width:100%; height:35px;" class="btn btn-sm text-light bg-dark">완료</button>
                {% else %}
                <div class="mb-3">
                    <label for="email">사용자 Email</label>
                    <input type="email" class="form-control" name="email" id="email"
                        value="{{'@naver.com'|lower}}">
                </div>
                <button type="submit" name="action" value="send_code" style="width:100%; height:35px;" class="btn btn-sm text-light bg-dark">코드 전송</button>
                {% endif %}
            </form>
        </div>
        <div class="col-lg-4">
            {% include "form_errors.html" %}
        </div>
    </div>
</div>
{% endblock %}


App_Auth/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
        {% if field.errors %}
        <div>
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
        </div>
        {% endif %}
    {% endfor %}
</div>
{% endif %}
{% if error %}
<br>
<div class="alert alert-danger">
    <strong>{{ error }}</strong>
</div>
{% elif info %}
<br>
<div class="alert alert-info">
    <strong>{{ info }}</strong>
</div>
{% elif success%}
<br>
<div class="alert alert-success">
    <strong>{{ success }}</strong>
</div>
{% endif %}

App_Auth/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class = "row">
        <div class = "col-lg-5">
            <form method="post" action="{% url 'App_Auth:login' %}">
                {% csrf_token %}
                <h2>로그인</h2>
                <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
                <div class="mb-3">
                    <label for="email">사용자 Email</label>
                    <input type="email" class="form-control" name="email" id="email"
                        value="{{'@naver.com'|lower}}">
                </div>
                <div class="mb-3">
                    <label for="password">비밀번호</label>
                    <input type="password" class="form-control" name="password" id="password">
                </div>
                <button type="submit" style="width:49%; height:35px;" class="btn btn-sm text-light bg-dark">로그인</button>
                <a href="{% url 'App_Userpage:email_check' %}" style="width:49%; height:35px;" class="btn btn-sm text-light bg-dark">비밀번호 찾기</a>
            </form>
        </div>
        <div class="col-lg-4">
            {% if error %}
            <br>
            <div class="alert alert-danger">
                <strong>{{ error }}</strong>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

App_Auth/templates/password_change.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class = "row">
        <div class = "col-lg-5">
            <form method="post" action="{% url 'App_Userpage:password_change_view' user.id %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="email">사용자 Email</label>
                    <input type="email" class="form-control" value="{{ user.email }}" readonly="true">
                </div>
                {% if not user_is_verificate%}
                <div class="mb-3">
                    <label for="password">기존의 비밀번호</label>
                    <input type="password" class="form-control" name="origin_password" id="origin_password">
                </div>
                {% endif %}
                <div class="mb-3">
                    <label for="password">새로운 비밀번호</label>
                    <input type="password" class="form-control" name="new_password" id="new_password">
                </div>
                <div class="mb-3">
                    <label for="password_check">새로운 비밀번호 확인</label>
                    <input type="password" class="form-control" name='password_check' id="password_check">
                </div>
                <button type="submit" style="width:100%; height:35px;" class="btn btn-sm text-light bg-dark mb-3">비밀번호 수정</button>
            </form>
        </div>
        {% if messages %}
        {% for message in messages %}
            <div class="row" style="margin:20px auto;">
            <div class="col-sm-12">
                <div class="alert alert-danger">
                <strong>{{ message.tags }}!</strong> {{ message.message }}
                </div>
            </div>
            </div>
        {% endfor %}
        {% endif %}
        <div class="col-lg-4">
            {% include "form_errors.html" %}
        </div>
    </div>      
</div>
{% endblock %}

App_Auth/templates/sign.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class = "row">
        <div class = "col-lg-5">
            <form method="post" action="{% url 'App_Auth:signup' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="email">사용자 Email</label>
                    <input type="email" class="form-control" name="email" id="email"
                           value="{{ form.email.value|default_if_none:'@naver.com' }}">
                </div>
                <div class="mb-3">
                    <label for="password1">비밀번호</label>
                    <input type="password" class="form-control" name="password1" id="password1"
                           value="{{ form.password1.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="password2">비밀번호 확인</label>
                    <input type="password" class="form-control" name="password2" id="password2"
                           value="{{ form.password2.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="user_name">이름</label>
                    <input type="text" class="form-control" name="user_name" id="user_name"
                    value="{{ form.user_name.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="user_tel">전화번호</label>
                    <input type="number" class="form-control" name="user_tel" id="user_tel"
                           value="{{ form.user_tel.value|default:'010' }}">
                </div>
                <div class="mb-3">
                    <label for="company" >회사명/회사코드</label>
                    <select name="company" class="form-control" id="company">
                        <option value="">회사명</option>
                        <option value="회사 1">회사 1</option>
                        <option value="회사 2">회사 2</option>
                        <option value="회사 3">회사 3</option>
                        <option value="회사 4">회사 4</option>
                        <option value="회사 5">회사 5</option>
                        <option value="회사 6">회사 6</option>
                    </select>                    
                </div>
                <button type="submit" style="width:100%; height:35px;" class="btn btn-sm text-light bg-dark mb-3">회원가입</button>
            </form>
        </div>
        <div class="col-lg-4">
            {% include "form_errors.html" %}
        </div>
    </div>      
</div>
{% endblock %}

App_Auth/templates/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class = "row">
        <div class = "col-lg-5">
            <form method="post" action="{% url 'App_Auth:signup' %}">
                <h2>회원 가입</h2>
                {% csrf_token %}
                {% if email %}
                <div class="mb-3">
                    <label for="email">사용자 Email</label>
                    <input type="email" class="form-control" name="email" id="email"
                        value="{{email}}" 
                    {% if email_verified == True %}
                        readonly="true">
                    </div>
                    {% else %}
                    <div class="mb-3">
                        <label for="number">인증 코드</label>
                        <input type="text" class="form-control" name="code" id="code" placeholder = "대소문자 구별">
                    </div>
                    <button type="submit" name="action" value="signup_check_code" style="width:100%; height:35px;" class="btn btn-sm text-light bg-dark">완료</button>
                    {% endif %}
                {% else %}

                <div class="mb-3">
                    <label for="email">사용자 Email</label>
                    <input type="email" class="form-control" name="email" id="email"
                        value="{{'@naver.com'|lower}}">
                </div>
                <button type="submit" name="action" value="signup_send_code" style="width:100%; height:35px;" class="btn btn-sm text-light bg-dark">코드 전송</button>
                {% endif %}
            </form>

            {% if email_verified == True %}
            <form method="post" action="{% url 'App_Auth:signup' %}">
                {% csrf_token %}
                <input type="hidden" class="form-control" name="email" id="email"
                        value="{{email}}">
                <div class="mb-3">
                    <label for="password">비밀번호</label>
                    <input type="password" class="form-control" name="password" id="password"
                           value="{{ form.password.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="password_check">비밀번호 확인</label>
                    <input type="password" class="form-control" name="password_check" id="password_check"
                           value="{{ form.password_check.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="name">이름</label>
                    <input type="text" class="form-control" name="name" id="name"
                    value="{{ form.name.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="phone_number">전화번호</label>
                    <input type="tel" class="form-control" name="phone_number" id="phone_number"
                           value="{{ form.phone_number.value|default:'010' }}">
                </div>
                <div class="mb-3">
                    <label for="company" >회사명/회사코드</label>
                    <select name="company" class="form-control" id="company">
                        <option value="">회사명</option>
                        <option value="회사 1">회사 1</option>
                        <option value="회사 2">회사 2</option>
                        <option value="회사 3">회사 3</option>
                        <option value="회사 4">회사 4</option>
                        <option value="회사 5">회사 5</option>
                        <option value="회사 6">회사 6</option>
                    </select>                    
                </div>
                <button name='action' value='signup' type="submit" style="width:100%; height:35px;" class="btn btn-sm text-light bg-dark mb-3">회원가입</button>
            </form>
            {%endif%}
        </div>
        <div class="col-lg-4">
            {% include "form_errors.html" %}
            
        </div>
    </div>      
</div>
{% endblock %}