App_Auth/urls.py
from django.urls import path
from . import Auth_views, EmailFunc
app_name = "App_Auth"

urlpatterns = [
    path('login/', Auth_views.login_view, name='login'),
    path('logout/', Auth_views.logout_view, name='logout'),
    path('sign/', Auth_views.SignupView.as_view(), name='signup'),
]

App_Files/urls.py
from django.urls import path
from .views import *

app_name='App_Files'

urlpatterns = [
    path('home', File_HomeView, name='File_Home'),
    path('<file_category_slug>/', File_in_CategoryView, name='File_in_category'),
    path('manager/<int:categoty_id>', FileManagerView, name = 'FileManager'),
    path('오류-로그/<int:error_id>', ErrorLogDetailView ,name = "ErrorLogDetail" )
]

App_Userpage/urls.py
from django.urls import path
from .Userpage_views import userpage_render_view, user_update_view, password_update_view, EmailVerificationView
app_name='App_Userpage'

urlpatterns = [
    path('detail/', userpage_render_view, name = 'userpage_render_view'),
    path('update/', user_update_view, name = 'user_update_view'),
    path('update/password/emailcheck', EmailVerificationView.as_view(), name='email_check'),
    path('update/<user_id>/password/<user_token>', password_update_view, name = 'password_update_view'),

]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from rest_framework.authtoken import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Board.urls')),
    path('auth/', include('App_Auth.urls')),
    path('file/',include('App_Files.urls')),
    path('user/', include('App_Userpage.urls')),
    path('api/', include('App_API.urls')),
    path("api/auth", views.obtain_auth_token, name="obtain_auth_token"),
    path('api_auth/', include('rest_framework.urls', namespace='rest_framework')) # DRF 웹 로그인 
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>장고 게시판</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<body>
<!-- 네비게이터 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <table width="100%">
            <tr>
                <td width="5%">
                    <a class="navbar-brand" href="/">Django</a>
                </td>
                <td width="15%">
                    <a href="/" class="nav-link text-light">장고 게시판</a>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>
                </td>
                <td width="50%"></td>
                <td width="10%">
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="nav navbar-nav ml-auto">     
                            {% if request.user.is_authenticated %}  
                            <a class="nav-link" href="{% url 'App_Userpage:userpage_render_view' %}"><i class="fas fa-user-plus"></i>{{ request.user.name }}</a>
                            <a class="nav-link" href="{% url 'App_Auth:logout' %}">Logout</a>
                            {% else %}
                            <a class="nav-link" href="{% url 'App_Auth:signup' %}"><i class="fas fa-user-plus"></i> Sign</a>
                            <a class="nav-link" href="{% url 'App_Auth:login' %}">Login</a>
                            {% endif %}
                        </ul>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</nav>
    <div class = "container mt-3">
        <div class = "row">
            <div class="col-sm-12 col-md-3 col-lg-2 p-2">
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/">Home</a>
                    {% for category in all_category%}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{{category.get_absolute_url}}">{{ category.name }}</a>
                    {% endfor %}
                    {% comment %} {% if user.company == 'admin' %} {% endcomment %}
                    {% if user.is_admin %}
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'App_Files:File_Home' %}">관리</a>
                    {% endif %}
                </div>
            </div>
            <div class="col-sm-12 col-md-9 col-lg-10 p-2">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>